apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "1.0"
    spec:
      containers:
      - image: "shocnt/store-frontend-instrumented-fixed:latest"
        name: frontend
