apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
#spec:
#  replicas: 1
#  template:
#    spec:
#      containers:
#      - name: 
#        image: shocnt/store-frontend-instrumented-fixed:latest
