apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: prod
  name: frontend
spec:
  selector:
    matchLabels:
      tags.datadoghq.com/env: prod
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: "blue"
    spec:
      containers:
      - image: shocnt/store-frontend-instrumented-fixed:blue
        name: frontend
        env:
          - name: DD_CLIENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: rum-token
                key: clientToken
          - name: DD_APPLICATION_ID
            valueFrom:
              secretKeyRef:
                name: rum-token
                key: applicationId
