apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: prod
  name: frontend
spec:
  selector:
    matchLabels:
      tags.datadoghq.com/env: prod
  strategy:
    blueGreen:
      activeService: frontend-active
      previewService: frontend-standby
      prePromotionAnalysis:
        templates:
        - templateName: trace-error-rate-frontend
        args:
        - {name: version, value: "green"}
      autoPromotionSeconds: 300
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: "green"
    spec:
      containers:
      - image: shocnt/store-frontend-instrumented-fixed:green
        name: frontend
        env:
          - name: DD_CLIENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: rum-token
                key: clientToken
          - name: DD_APPLICATION_ID
            valueFrom:
              secretKeyRef:
                name: rum-token
                key: applicationId
