apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/service: store-frontend
    tags.datadoghq.com/env: "development"
    tags.datadoghq.com/version: "1.0"
    app: ecommerce
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tags.datadoghq.com/service: store-frontend
      tags.datadoghq.com/env: "development"
      tags.datadoghq.com/version: "1.0"
      app: ecommerce
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 1
      steps:
        - setWeight: 25
        - pause: {}  
  template:
    metadata:
      labels:
        tags.datadoghq.com/service: store-frontend
        tags.datadoghq.com/env: "development"
        tags.datadoghq.com/version: "1.0"
        app: ecommerce
      annotations:
        ad.datadoghq.com/frontend.logs: '[{"source": "ruby", "service": "store-frontend"}]'
        ad.datadoghq.com/frontend.tags: '{"team": "frontend"}'
    spec:
      containers:
      - args:
        - docker-entrypoint.sh
        command:
        - sh
        env:
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: pw
                name: db-password
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_ANALYTICS_ENABLED
            value: "true"
          - name: DISCOUNTS_ROUTE
            value: "http://discounts"
          - name: DISCOUNTS_PORT
            value: "5001"
          - name: ADS_ROUTE
            value: "http://advertisements"
          - name: ADS_PORT
            value: "5002"
          # Enable RUM
          # - name: DD_CLIENT_TOKEN
          #   value: <your_client_token>
          # - name: DD_APPLICATION_ID
          #   value: <your_application_id>
        image: "shocnt/store-frontend-instrumented-fixed:latest"
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits: {}
