apiVersion: v1
kind: Service
metadata:
  labels:
    tags.datadoghq.com/service: store-frontend
    tags.datadoghq.com/env: development
    tags.datadoghq.com/version: "1.0"
    app: ecommerce
  name: frontend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  selector:
    tags.datadoghq.com/service: store-frontend
    tags.datadoghq.com/env: development
    tags.datadoghq.com/version: "1.0"
    app: ecommerce
  type: ClusterIP
